### ISSUE TITLE
Doesn't seem to work anymore

### ISSUE THREAD

**Issue by itsfenix** [anubiann00b/AnimeDownloader#4]
Okay first off, I like the idea. Can I suggest you make it possible to DL a range of episodes instead of just one at a time.

Moving on:
File "anime-downloader.py", line 102, in <module>
    download_anime(sys.argv[1], sys.argv[2])
  File "anime-downloader.py", line 36, in download_anime
    anime_name, anime_score = process.extractOne(anime_name_input, animes)
TypeError: 'NoneType' object is not iterable

Is what I get running on Ubuntu 14.04 LTS. If you guys are still maintaining this
Yes, all dependencies are satisfied in requirements

**Comment by anubiann00b** [comment]
oh :P

I'll try to get to it this weekend hopefully. Their website probably changed again.

Thanks. I really appreciate you bringing up an issue.

**Comment by itsfenix** [comment]
No problem. Thanks for putting the work in! If you need someone to do some testing or even more ideas let me know.

**Comment by anubiann00b** [comment]
Definitely would be appreciated when I get back into this. Out of curiosity, how did you find this repo?

**Comment by itsfenix** [comment]
Well, I found animepremium.tv's site hosts a lot of anime for the public to DL and wondered if anyone had written any scraper for it, so just googled and found this repo. It would be great because i'm not really a fan of torrenting, and some of the stuff on animepremium is hard to find torrents for.

Additionally I was interested because i'm writing a private NodeJS app that is a bit similar to your repo but the goal is different and for my personal use.

Like I said let me know, i'd be happy to help out.

**Comment by anubiann00b** [comment]
Chia Anime changed their site structure, have fixed that. animepremium.tv is currently down though...?

Once it's back up it should work.

e16a56f

**Comment by itsfenix** [comment]
My bad, I was referring to http://www.animepremium.net/index.php, could be a better choice for host since it doesnt rely on ripping stream links but just has the DLs organized nicely for you

**Comment by anubiann00b** [comment]
Oh hmm this might be a better site to use... But login/subscription...

**Comment by itsfenix** [comment]
Yeahh they seem to say subscription but if you log in there is no payment. A bit strange but hey benefits us. As for login you can just parameterize the login/pw and authenticate from within your client. Could be good

**Comment by JordekFluffball** [comment]
Checked it out, they give you a 1 day trial and then you have to pay. Don't bother with it.

**Comment by anubiann00b** [comment]
Hmmm ok. I'll close this one then, unless there's more?
